project/project/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('bulk-mail-sender/super-user/auth/admin/', admin.site.urls),
    path('',include('mainapp.urls')),
    path('',include('user.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project/user/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.auth.decorators import login_required
from django.conf import settings
from django.conf.urls.static import static


from . import views

urlpatterns = [
    # path('login',views.login,name='login'),
    path('sendmail',views.sendMail ,name='sendmail'),
    path('registration',views.registration,name='registration'),
    path('otp-varification',views.varifyotp,name='otpvarify'),
    path('register',views.register,name='register'),
    path('uploadfile',views.uploadfile,name='uploadfile'),
    path('login', LoginView.as_view(template_name='login.html'), name='login'),
    path('logout', LogoutView.as_view(template_name='index.html'), name='logout'),
    path('password-reset', views.resetPassword, name='passwordreset'),
    path('change-Password', views.changePassword, name='changePassword'),
    path('profile', login_required(views.profile), name='profile'),
    path('compose-mail', views.composeMail,name='composeMail'),
    path('delete-file/<int:id>',views.deletefile,name='delete'),
    path('update-file/<int:value>/<int:id>',views.updatefile,name='update')


]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project/user/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.

class receiverFileModel(models.Model):
      file = models.FileField( upload_to='reciever/', max_length=100)
      author = models.ForeignKey(User,  on_delete=models.CASCADE)


class senderFileModel(models.Model):
      file = models.FileField( upload_to='sender/', max_length=100)
      esp = models.CharField(default='', max_length=50)
      port = models.PositiveIntegerField(choices=((465, "465 (Secure - Recommended)"),(587, "587 (Secure - STARTTLS"),(25, "25 (Unsecure - Not Recommended)")), default=465) 
      author = models.ForeignKey(User,  on_delete=models.CASCADE)
    

project/user/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import receiverFileModel,senderFileModel


CHOICES = {465: "465 (Secure - Recommended)"}


class UserRegisterForm(UserCreationForm):

    class Meta:
        model = User
        fields = [
            'username', 'password1', 'password2'
        ]

class senderFileForm(forms.ModelForm):
    class Meta:
        model = senderFileModel
        fields = "__all__"
    
    def __init__(self, *args, **kwargs):
        super(senderFileForm, self).__init__(*args, **kwargs)
        self.fields['file'].widget.attrs['accept'] = '.csv, .txt'
        self.fields['file'].widget.attrs['class'] = 'form-control'
        self.fields['esp'].widget.attrs['class'] = 'form-control'
        self.fields['esp'].widget.attrs['placeholder'] = 'ex. mail.geeektheo.com'
        self.fields['port'].widget=forms.RadioSelect(choices = CHOICES)

class receiverFileForm(forms.ModelForm):
    class Meta:
        model = receiverFileModel
        fields = "__all__"
    def __init__(self, *args, **kwargs):
        super(receiverFileForm, self).__init__(*args, **kwargs)
        self.fields['file'].widget.attrs['class'] = 'form-control'
        self.fields['file'].widget.attrs['accept'] = '.csv, .txt'

project/user/views.py
from django.shortcuts import render,redirect,HttpResponse
from .forms import UserRegisterForm,receiverFileForm,senderFileForm
from django.contrib.auth.models import User
from .models import senderFileModel,receiverFileModel
from django.views.generic import ListView
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from .tasks import signup_otp, signup_success,pass_reset_otp
import random



def sendMail(request):
      if request.method == "POST":
            otp = random.randrange(11111, 99999)
            email = request.POST.get('email', False)

            if User.objects.filter(username=email).first():
                  messages.success(request,'Email is already registered')
                  return redirect(registration)

            else : 
                  task = signup_otp(email,otp) 
                  if task == True:
                        request.session['otp'] = otp
                        request.session['email'] = email
                        messages.success(request,'Otp sent ')
                        return redirect(registration)
      return redirect('login')

def registration(request):

      return render(request,"emailvarify.html")

def varifyotp(request):
      if request.method == 'POST':
            s_otp = request.session['otp']
            email = request.session['email']
            otp = request.POST['userotp']
            if int(otp) == (s_otp):

                  messages.success(request,'OTP Verify SuccessFully...')
                  return redirect(register)
            else:
                  messages.success(request,'Wrong OTP Please Try Again')
                  return render(request,"emailvarify.html")
                  
def register(request):
      if request.method == "POST":
             
            u_fm = UserRegisterForm(request.POST, instance=request.user.id)
            try:
                  if request.session['otp']:
                        del request.session['otp']
                  if request.session['email']:
                        del request.session['email']
            except:
                  pass

            if u_fm.is_valid():
                  username = request.POST['username']
                  request.session['Username'] = username
                  u_fm.save()

                  email = request.session['Username']
                  try:
                        task = signup_success(email)
                  except:
                        pass
                  messages.success(request,'Sing-Up SuccessFully...')

                  return redirect("login")
            else:
                  pass
            
      form = UserRegisterForm()
      return render(request,"register.html",{'form':form})


@login_required
def profile(request):  
      user = request.user
      file = senderFileModel.objects.get(author=user)
      receiverfile = receiverFileModel.objects.all()
      context = {'file':file, "receiver":receiverfile}

      return render(request, 'profile.html',context)

def resetPassword(request):
      if request.method == "POST":
            otp = random.randrange(11111, 99999)
            email = request.POST.get('email', False)
            task = pass_reset_otp(email,otp)
            request.session['otp'] = otp
            request.session['email'] = email
            return render(request,"passwordReset.html",{'temp':'temp'}  )
      
      return render(request,'passwordReset.html')

def changePassword(request):
      if request.method == "POST":
            password1 = request.POST['password1'] 
            password2 = request.POST['password2']
            user_otp = request.POST['userotp']
            email = request.session['email']
            otp = request.session['otp']
            if int(user_otp) == otp:
                  if password1 == password2:
                        user = User.objects.get(username=email )
                        user.set_password(password1)
                        user.save()
                        messages.success(request,'Password changed successfully')
                        del request.session['email']
                        del request.session['otp']
                        return redirect("login")
            else:
                  messages.error(request,'wrong otp please try again')
                  return render(request,'passwordReset.html')
      return render('home')
                   
                  



@login_required
def uploadfile(request):
      form1 = senderFileForm()
      form2 = senderFileForm()
      temp = False

      if request.method == "POST":
            value = request.POST['value']
            
            if int(value) == 1:
                  user = request.user
                  file = request.FILES['file']
                  esp = request.POST['esp']
                  port = request.POST['port']
                  model = senderFileModel.objects.all()
                  for i in model:
                        if request.user==i.author:
                              i.delete()
                  senderFileModel.objects.create(file=file,author=user,esp=esp,port=port)
                  messages.success(request,' Sender Email File Uploaded successfully')
                  temp = True

            elif int(value) == 2:
                  user = request.user
                  file = request.FILES['file']
                  receiverFileModel.objects.create(file=file,author=user)
                  messages.success(request,'Recipients Email File Uploaded successfully')
                  temp = True

      context = {'form1':form1,'form2':form2}

      return render(request,'uploadfiles.html',context)


#to delete file from user action
def deletefile(request,id):
      
      receiverFileModel.objects.get(id=id).delete()

      return redirect('profile')


def updatefile(request,id,value):
      if value == 0:
            data = senderFileModel.objects.get(id=id)
            sender = []
            if request.user == data.author:
                  with open(data.file.path,"r") as f:
                        f=f.read().splitlines()
                        for email in f:
                              sender.append(email.split(','))
            sender.sort()
            datalist = dict(sender)
            x=0
            return render(request,'updatefile.html',{'data':datalist,'x':x})


      elif value == 1:
            data = receiverFileModel.objects.get(id=id)
            datalist = []
            if request.user == data.author:
                  with open(data.file.path) as f:
                        f=f.read().splitlines()
                        datalist = list(f)
                  x=1
            datalist.sort()
            return render(request,'updatefile.html',{'data':datalist,'x':x})


@login_required
def composeMail(request):
      user = request.user
      listfile=[]
      try:
            files = receiverFileModel.objects.all()
            for file in files:
                  if file.author == user:
                        listfile.append(file)
            return render(request,'composeMail.html',{'files':listfile})
            
      except:
            messages.error(request,'Please first upload Recipients list ')

      return render(request,'composeMail.html')

project/user/templates/composeMail.html
{% extends "base.html" %}

{% block composemail_active %}active{% endblock composemail_active %}

{% block style %}
input::placeholder {
color: red;
/* Main rule for modern browsers */
}

textarea::placeholder {
color: red;
/* Main rule for modern browsers */
}

{% endblock style %}
{% block content %}
{% load my_tags %}


<br><br><br>


<div class="container-fluid">

      <div style=" display:flex; background-color: rgb(26, 30, 33);" class="row">

            <div class="col col-sm-12 rounded">

                  <h3 class="pl-4">Compose mail</h3>

                  <form class="m-4 p-3 border rounded row " style="border:1px solid white ;" method="post" action="{% url 'mail' %}">
                        <div class="col col-sm-4">
                              <label for="subject">Subject:</label>
                              <input required style="color: white;background-color: rgb(32, 29, 29);" type="text" name="subject" id="id_subject" class="form-control input">
                              <br>

                              <label for="message">Message:</label>
                              <textarea required style="color: white;background-color: rgb(32, 29, 29)" class="form-control" name="message" id="id_message" cols="30" rows="10"></textarea>
                              <p><i>You can use html tags inside message to design mail</i></p>
                              <br>
                              <label for="number">Choose, one email how many time send mail</label>
                              <input required style="color: white;background-color: rgb(32, 29, 29)" type="number" name="number" id="id_number" class="form-control input">
                              <p>Number shuold be less than 200.</p>

                        </div>
                        {% if files %}

                        <div class="col col-sm-7 offset-1">
                              <input onclick="showFileOption()" type="checkbox" id='check_file'> <label for="check_file"> Choose File</label><br>
                              <input onclick="showTextarea()" type="checkbox" id='check_email'> <label for="check_email"> Write Emails</label>

                              <div style="display: none;" id='choose_file' class="col col-5">

                                    <h4><label for="type">choose file to send mail</label></h4>
                                    <select style="color: white;background-color: rgb(32, 29, 29)" class='form-select' name="file" id="id_file">
                                          <option disabled selected value="">Select</option>

                                          {% for file in files %}
                                          <option value="{{ file.id }}">{{ file.file.name }}</option>

                                          {% endfor %}
                                    </select>


                              </div>
                              <div style="display:none;" id="email_area" class="  col col-7">
                                    <textarea placeholder="Write or past Emails here" style=" color: white;background-color: rgb(32, 29, 29)" class="form-control" name="email_area" id="id_textarea" cols="50" rows="10"></textarea>
                              </div>
                              <br>
                              <div class="col col-5">
                                    <label for="task_name"> Name for task to remember :</label>
                                    <input title='Name for task to remember it' required style="color: white;background-color: rgb(32, 29, 29)" type="Text" name="task_name" id="id_task" class="form-control input">
                              </div>


                        </div>
                        {% else %}

                        <div class="col col-sm-7 offset-1">
                              <h4>Please Upload Recipients listFile</h4>
                              <a class="btn btn-secondary" href="{% url 'uploadfile' %}">Upload file</a>
                              <input required value='' type="hidden">
                        </div>

                        {% endif %}
                        <hr>
                        <div class="row">
                              <div class="col col-5"></div>
                              <div class="col-3  align-items-center">
                                    <input type="submit" class="btn btn-primary" value="Send Mail">
                              </div>
                        </div>


                        {% csrf_token %}
                  </form>


            </div>
            <div class="col col-6 offset-1">

            </div>
      </div>
</div>
<!-- Bootstrap JS (optional) -->

<script>


      function showFileOption() {
            document.getElementById("check_email").checked = false
            document.getElementById("choose_file").style.display = 'block'
            document.getElementById("email_area").style.display = 'none'


            document.getElementById("id_file").required = true
            document.getElementById("id_textare").required = false

      }

      function showTextarea() {
            document.getElementById("check_file").checked = false
            document.getElementById("choose_file").style.display = 'none'
            document.getElementById("email_area").style.display = 'block'


            document.getElementById("id_file").required = false
            document.getElementById("id_textare").required = true
      }
</script>
{% endblock content %}

project/user/templates/emailvarify.html
{% extends 'base.html' %}
{% block register_active %}active{% endblock register_active %}

{% block content %}

{% load widget_tweaks %}



{% load crispy_forms_tags %}
<!DOCTYPE html>
<html lang="en">

  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <style>
      .box {
        background-color: rgb(33, 37, 41);
        border: 1px solid white;
        padding: 30px;
        border-radius: 20px;
        width: 450px
      }


      .inputbox {
        margin: 40px;
        position: relative;
      }

      input {
        border: 1px solid white;
        border-radius: 8px;
        outline: none;
        background: #1c1c1c;
        color: white;
        height: 40px;
        width: 300px;
        transition-duration: 600ms;

      }

      input[type=number]::-webkit-inner-spin-button,
      input[type=number]::-webkit-outer-spin-button {
        -webkit-appearance: none;
      }

      input[type=submit] {
        background: rgb(60, 60, 60);
        width: 100px;
        transition-duration: 200ms;
      }

      input[type=submit]:hover {
        background-color: black;

      }

      input[type=submit]:active {
        background-color: rgb(30, 30, 30);
      }

      .label {
        position: absolute;
        top: 3px;
        left: 20px;
        font-size: 20px;
        cursor: auto;
        transition-duration: 600ms;
        height: 14px;
      }

      .input:focus,
      .input:not(:placeholder-shown).input:not(:focus) {
        border: 1px solid rgb(121, 183, 208);
      }

      .input:focus~.label,
      .input:not(:placeholder-shown).input:not(:focus)~.label {
        top: -12px;
        left: 10px;
        font-size: 15px;
        color: rgb(121, 183, 208);
        background-color:rgb(33, 37, 41);
      }

      .row {
        margin-left: 10px;
        margin-top: -20px;
        color: rgb(121, 183, 208);
      }

      a {
        text-decoration: underline;
        color: rgb(121, 183, 208);
        text-decoration: dotted;
      }

      a:hover {
        color: rgb(174, 217, 234);
      }

      a:active {
        color: red;
      }

      .alert {
        background-color: rgb(125, 16, 16);
        height: 40px;
        padding: 5px;
        color: rgb(23, 2, 2);

      }

      .btn-close {
        border: 1px solid black;
        opacity: 1;
        width: 10px;
        height: 5px;

      }

      .hrdiv {
        display: flex;
        margin-bottom: 20px;
      }

      hr {
        width: 200px
      }

      .image {
        width: 50px;
        height: 43px;
        margin-top: 2px;
        margin-left: -22px;
        border-radius: 5px;
        padding-right: 3px;
      }

      .login-with {
        border: 2px solid rgb(70, 100, 220);
        background-color: rgb(70, 100, 220);
        width: 225px;
        height: 50px;
        overflow: hidden;
        color: white;
        border-radius: 4px;
        margin: 20px;
      }

      .login-link {
        color: rgb(255, 255, 255);
        font-weight: bold;
        text-decoration: none;
      }

      .login-link:active {
        color: white;
      }

      .bi {
        position: absolute;
        margin-left: -25px;
        margin-top: 5px;
      }
    </style>
  </head>
  <br><br><br>

  <center>
   

    {% if request.session.email %}


    <form method="post" action="{% url 'otpvarify' %}">

      

      <div class="box">

        <h3>We sent OTP on your Email </h3>

        <div class="inputbox">
          <input type="email" readOnly class="input" value='{{ request.session.email}}' placeholder=" " id="email">
          <label class="label" for="email"> Email</label>
        </div>

        <div id="otpbox" class="inputbox">

          <input required type="number" name="userotp" class="input" placeholder=" " id="otp">
          <label class="label" for="otp">Ener OTP here</label>
        </div>
        <div class="row ">
          <div class="col ">

          </div>

        </div>

        <div class="inputbox">
          <input type="submit" id="varify" class="input" value="Varify">
        </div>

      </div>
      {% csrf_token %}
    </form>

    {% else %}

    <form method="post" action="sendmail">
      <div class="box">
        <h3>Enter your Email for varification</h3>

        <div class="inputbox">
          <input type="email" name='email' required class="input" placeholder=" " id="email">
          <label class="label" for="email"> Email</label>
        </div>
        <div class="row ">
          <div style="margin-left:-70px;" class="col ">
            <a href="{% url 'login' %}">Already have an account!</a>
          </div>
        </div>


        <div class="inputbox">
          <input type="submit" id="send_otp" class="input" value="Send OTP">
        </div>

      </div>
      {% csrf_token %}

    </form>
    {{form}}

    {% endif %}

  </center>
  {% csrf_token %}

  <script>
    function myfunction() {
      let a = document.getElementById('id_email').value;
      for (let i in a) {
        if (1 == 1) {
        }
      }
    }
    
  </script>
  {% endblock content %}

project/user/templates/login.html
{% extends 'base.html' %}

{% block login_active %}active{% endblock login_active %}

{% block content %}
<!DOCTYPE html>
<html lang="en">

  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <style>
      body {
        background-color: rgb(28, 28, 28);
      }

      .box {
        background-color: rgb(33, 37, 41);
        border: 1px solid white;
        padding: 30px;
        border-radius: 20px;
        width: 450px
      }


      .inputbox {
        margin: 40px;
        position: relative;
      }

      input {
        border: 1px solid white;
        border-radius: 8px;
        outline: none;
        background: #1c1c1c;
        color: white;
        height: 40px;
        width: 300px;
        transition-duration: 600ms;

      }

      input[type=number]::-webkit-inner-spin-button,
      input[type=number]::-webkit-outer-spin-button {
        -webkit-appearance: none;
      }

      input[type=submit] {
        background: rgb(60, 60, 60);
        width: 100px;
        transition-duration: 200ms;
      }

      input[type=submit]:hover {
        background-color: black;

      }

      input[type=submit]:active {
        background-color: rgb(30, 30, 30);
      }

      .label {
        position: absolute;
        top: 3px;
        left: 20px;
        font-size: 20px;
        cursor: auto;
        transition-duration: 600ms;
        height: 14px;
      }

      .input:focus,
      .input:not(:placeholder-shown).input:not(:focus) {
        border: 1px solid rgb(121, 183, 208);
      }

      .input:focus~.label,
      .input:not(:placeholder-shown).input:not(:focus)~.label {
        top: -12px;
        left: 10px;
        font-size: 15px;
        color: rgb(121, 183, 208);
        background-color:rgb(33, 37, 41);
      }

      .row {
        margin-left: 10px;
        margin-top: -20px;
        color: rgb(121, 183, 208);
      }

      a {
        text-decoration: underline;
        color: rgb(121, 183, 208);
        text-decoration: dotted;
      }

      a:hover {
        color: rgb(174, 217, 234);
      }

      a:active {
        color: red;
      }

      .alert {
        background-color: rgb(125, 16, 16);
        height: 40px;
        padding: 5px;
        color: rgb(23, 2, 2);

      }

      .btn-close {
        border: 1px solid black;
        opacity: 1;
        width: 10px;
        height: 5px;

      }

      .hrdiv {
        display: flex;
        margin-bottom: 20px;
      }

      hr {
        width: 200px
      }

      .image {
        width: 50px;
        height: 43px;
        margin-top: 2px;
        margin-left: -22px;
        border-radius: 5px;
        padding-right: 3px;
      }

      .login-with {
        border: 2px solid rgb(70, 100, 220);
        background-color: rgb(70, 100, 220);
        width: 225px;
        height: 50px;
        overflow: hidden;
        color: white;
        border-radius: 4px;
        margin: 20px;
      }

      .login-link {
        color: rgb(255, 255, 255);
        font-weight: bold;
        text-decoration: none;
      }

      .login-link:active {
        color: white;
      }

      .bi {
        position: absolute;
        margin-left: -25px;
        margin-top: 5px;
      }
    </style>
  </head>

  <body>
    <center><br><br><br><br>
      
      
      <form action="" method="POST">


        <div class="box">
          
          <h3> Bulk Mail Sender</h3>
          <h4 style='color:rgb(174, 217, 234)'> LOGIN</h4>
          <div class="inputbox">
            <input required class="input"  placeholder=" " type="text" id="username" name="username">
            <label class="label" id='label' for="username">Username</label>
            <p><i>Sing-up email is Your Username</i></p>
          </div>
          <div class="inputbox">
            <input required class="input" type="password" placeholder=" " name="password" id="password" />

            <label class="label" for="password">Password</label>
            <i class="bi bi-eye-slash" id="togglePassword"></i>
          </div>
          <div class="row ">
            <div class="col">
              <a href="{% url "passwordreset" %}">Forgot Password?</a>
            </div>
            <div class="col">
              <a href="{% url 'registration' %}">Sign-up</a>
            </div>
          </div>



          <div class="inputbox">
            <input class="submit btn-primary" type="submit" name="btn" id="submit" value='Login'>

          </div>

        </div>
        {% csrf_token %}
      </form>

      <script>       

        const togglePassword = document.querySelector("#togglePassword");
        const password = document.querySelector("#password");

        togglePassword.addEventListener("click", function () {
          // toggle the type attribute
          const type = password.getAttribute("type") === "password" ? "text" : "password";
          password.setAttribute("type", type);

          // toggle the icon
          this.classList.toggle("bi-eye");
        });
      </script>

    </center>
  </body>

</html>
{% endblock content %}

project/user/templates/uploadfiles.html
{% extends "base.html" %}

{% load widget_tweaks %}
{% load crispy_forms_tags %}

{% block uploadfile_active %}active{% endblock uploadfile_active %}


{% block content %}

<div class="container "><br><br>

      <div class="row">
            <div style="border: 2px solid gray; border-radius : 30px;" class=" border-light col-sm-5">
                  <form class='p-3' method="post" enctype="multipart/form-data" action="">
                        <h4>Sender Emails </h4>

                        <label>Select File that Containing Email & Password That Will be Used To Send Mail<br> <br>Choose Only CSV/TXT </label>
                        <br>
                        {{form1.file}}<br>

                        <label for="id_esp">Choose Email service provide(ESP)</label>
                        {{ form2.esp }}<br>

                        <label for="id_port">Port number</label><br>
                        {{ form1.port }}<br><br>

                        <input type="hidden" value="{{ user.username }}" name="author" id='id_author'>

                        <input type="hidden" name="value" value="1">
                        <!-- <input accept=".csv, .txt" type="file" id="id_file" name="file"><br><br> -->
                        <button class="btn btn-secondary bg-dark">Upload File</button>

                        {% csrf_token %}

                  </form>

            </div>
            <div style="border: 2px solid gray; border-radius: 30px;" class="border-light col-sm-5 offset-2">
                  <form class='p-2' method="post" enctype="multipart/form-data" action="">

                        <br>
                        <h4>Recipient Emails </h4>


                        <p>Choose Recipients Emails list to Receive Mail<br> Choose Only CSV/TXT </p>
                        <br><br>
                        {{form2.file}}
                        <input type="hidden" value="{{ user.username }}" name="author" id='id_author'>

                        <br><br>
                        <input type="hidden" name="value" value="2">

                        <!-- <input accept=".csv, .txt" type="file" id="id_file" name="file"><br><br> -->
                        <button class="btn btn-secondary bg-dark">Upload File</button>

                        {% csrf_token %}
                  </form>

            </div>
      </div>

      {% endblock content %}